export const LOGOUT = "LOGOUT";
export const EMPLOYEE_LOGIN = "EMPLOYEE_LOGIN";
export const SAVE_EMPLOYEE_DETAILS = "SAVE_EMPLOYEE_DETAILS";
export const LOADING = "LOADING";
export const GET_ALL_EMPLOYEE_DETAILS = "GET_ALL_EMPLOYEE_DETAILS";
export const SET_TOKEN = "SET_TOKEN";
export const CONNECTED_EMPLOYEE = "CONNECTED_EMPLOYEE";

